function referenciasDeQuestoes(area, posicao) {
  const inicios = {
    linguagens: 1,
    humanas: 46,
    natureza: 91,
    matematica: 136
  };

  if (!inicios[area]) return [];

  const anos = [2024, 2023, 2022, 2021, 2020];

  const anoA = anos[posicao % anos.length];
  const anoB = anos[(posicao + 2) % anos.length];

  const indiceA = inicios[area] + ((posicao * 3) % 30);
  const indiceB = inicios[area] + ((posicao * 7 + 11) % 30);

  return [
    { ano: anoA, indice: indiceA },
    { ano: anoB, indice: indiceB }
  ];
}

function criarTopico(
  area,
  posicao,
  id,
  titulo,
  resumo,
  nivel,
  texto,
  dica
) {
  return {
    id,
    titulo,
    resumo,
    nivel,
    texto,
    dica,
    questoesRelacionadas: referenciasDeQuestoes(area, posicao)
  };
}

window.CONTEUDOS = {
  linguagens: {
    materia: "linguagens",
    nome: "Linguagens, Códigos e suas Tecnologias",
    icone: "🗣️",
    cor: "#7c3aed",
    descricao:
      "Leitura, interpretação, gramática, literatura e análise das diferentes práticas de linguagem.",
    topicos: [
      criarTopico("linguagens", 0, "interpretacao-textos", "Interpretação de textos", "Compreenda informações explícitas, inferências, tema, conclusão e intenção comunicativa.", "Essencial", "<p>A interpretação exige relação entre o texto, o contexto e as escolhas linguísticas do autor. Informações explícitas estão escritas; inferências são conclusões construídas a partir de indícios. Observe também recursos visuais, título, ironia, interlocução e finalidade.</p>", "Elimine alternativas que ampliam o sentido, invertem a ideia ou trazem informações fora do texto."),
      criarTopico("linguagens", 1, "tipos-generos-textuais", "Tipos e gêneros textuais", "Diferencie narração, descrição, dissertação, exposição e injunção.", "Essencial", "<p>Os tipos textuais correspondem a estruturas predominantes: narração organiza ações no tempo; descrição detalha características; dissertação defende ponto de vista; exposição explica; injunção orienta. Gêneros são formas sociais concretas, como notícia, crônica, resenha, anúncio e meme.</p>", "A situação de comunicação e o lugar de circulação ajudam a reconhecer o gênero."),
      criarTopico("linguagens", 2, "funcoes-linguagem", "Funções da linguagem", "Identifique referencial, emotiva, conativa, fática, metalinguística e poética.", "Essencial", "<p>Na função referencial predomina o conteúdo; na emotiva, o emissor; na conativa, o receptor; na fática, o contato; na metalinguística, a própria linguagem; na poética, a organização especial da mensagem.</p>", "Descubra qual elemento da comunicação está em destaque."),
      criarTopico("linguagens", 3, "figuras-linguagem", "Figuras de linguagem", "Analise metáfora, metonímia, ironia, hipérbole, personificação e antítese.", "Essencial", "<p>As figuras produzem efeitos de sentido. Metáfora cria relação de semelhança; metonímia substitui por contiguidade; ironia sugere o contrário; hipérbole exagera; personificação atribui ação humana; antítese aproxima opostos.</p>", "No ENEM, o mais importante é explicar o efeito produzido, não apenas nomear a figura."),
      criarTopico("linguagens", 4, "semantica", "Semântica", "Estude polissemia, sinonímia, ambiguidade, pressuposição e implicatura.", "Essencial", "<p>A polissemia permite vários sentidos para uma palavra; a ambiguidade gera dupla interpretação; pressuposições são informações pressupostas; implicaturas são sentidos sugeridos pelo contexto.</p>", "Volte sempre ao contexto antes de definir o sentido de uma expressão."),
      criarTopico("linguagens", 5, "fonetica-fonologia", "Fonética e fonologia", "Diferencie fonemas, letras, dígrafos, sílabas e acentuação.", "Essencial", "<p>Fonema é o menor som capaz de diferenciar palavras; letra é a representação gráfica. Dígrafos representam um único fonema, como nh e lh. A divisão silábica e os acentos gráficos também podem ser cobrados.</p>", "Palavras mínimas ajudam a perceber fonemas diferentes."),
      criarTopico("linguagens", 6, "morfologia", "Morfologia e classes de palavras", "Reconheça classes variáveis e invariáveis e os processos de formação de palavras.", "Essencial", "<p>Substantivo, verbo, adjetivo, artigo, numeral e pronome são variáveis. Advérbio, conjunção, preposição e interjeição são invariáveis. Derivação, composição e outros processos ampliam o vocabulário.</p>", "Analise a função da palavra no período, e não somente o seu significado isolado."),
      criarTopico("linguagens", 7, "sintaxe", "Sintaxe e período composto", "Identifique termos da oração, período simples, coordenação e subordinação.", "Essencial", "<p>A sintaxe estuda a relação entre os termos. No período composto, orações coordenadas têm independência sintática; subordinadas dependem de uma oração principal ou outra subordinada.</p>", "Procure os verbos para separar as orações."),
      criarTopico("linguagens", 8, "concordancia", "Concordância verbal e nominal", "Revise regras de concordância com sujeito simples, composto, partitivo e coletivo.", "Essencial", "<p>O verbo concorda com o núcleo do sujeito. Expressões partitivas e coletivos costumam atrair a concordância, mas também podem manter o plural. Na concordância nominal, observam-se adjuntos, pronome e flexões especiais.</p>", "Localize primeiro o núcleo do sujeito."),
      criarTopico("linguagens", 9, "regencia-crase-pontuacao", "Regência, crase e pontuação", "Domine verbos e preposições, o uso do a craseado e os sentidos da pontuação.", "Essencial", "<p>A regência é a relação entre termos governados por verbos, substantivos e adjetivos. Crase é a fusão da preposição a com o artigo a. A pontuação organiza, pausa e pode alterar sentidos.</p>", "Troque a crase por para: se fizer sentido, provavelmente a crase está correta."),
      criarTopico("linguagens", 10, "literatura-ate-romantismo", "Literatura até o Romantismo", "Estude Trovadorismo, Humanismo, Classicismo, Quinhentismo, Barroco, Arcadismo e Romantismo.", "Essencial", "<p>As literaturas antigas dialogam com o contexto histórico, religioso e social. O Barroco apresenta conflito e lirismo; o Arcadismo valoriza a natureza idealizada; o Romantismo exalta sentimentos, nacionalidade e liberdade.</p>", "Relacione escola literária, contexto histórico e características estéticas."),
      criarTopico("linguagens", 11, "modernismo-literatura-contemporanea", "Modernismo e literatura contemporânea", "Analise a Semana de 1922, as fases modernistas e a produção pós-modernista.", "Essencial", "<p>O Modernismo brasileiro rompe com modelos europeus e propõe linguagem renovada, nacionalidade crítica e liberdade formal. A poesria contemporânea amplia temas urbanos, indígenas, femininos e das margens.</p>", "Observe ruptura estética e relação com a identidade brasileira.")
    ]
  },

  humanas: {
    materia: "humanas",
    nome: "Ciências Humanas e suas Tecnologias",
    icone: "🌎",
    cor: "#2563eb",
    descricao:
      "História, Geografia, Filosofia, Sociologia e formação política para interpretar a sociedade.",
    topicos: [
      criarTopico("humanas", 0, "pre-historia-antiguidade", "Pré-história e Antiguidade", "Compreenda o surgimento da agricultura, das cidades e das civilizações antigas.", "Essencial", "<p>A Pré-história estuda sociedades sem escrita. A Revolução Neolítica fixou grupos humanos e possibilitou excedentes. Mesopotâmia, Egito, Grécia e Roma organizaram Estado, escrita, leis, religião e comércio.</p>", "Relacione cada civilização às suas condições geográficas e organização social."),
      criarTopico("humanas", 1, "idade-media-renascimento", "Idade Média e Renascimento", "Estude feudalismo, Igreja, Cruzadas, cidades medievais, humanismo e novas artes.", "Essencial", "<p>A Idade Média europeia foi marcada por feudalismo e forte influência da Igreja. O Renascimento valorizou o humanismo, a razão, a arte perspectivada e as novas descobertas científicas.</p>", "Perceba a transição do teocentrismo para o antropocentrismo."),
      criarTopico("humanas", 2, "absolutismo-revolucoes", "Absolutismo e Revoluções", "Analise o Estado absolutista, o liberalismo e as revoluções inglesa, americana e francesa.", "Essencial", "<p>O absolutismo concentrava poder no monarca. As revoluções burguesas limitaram o poder régio, ampliaram direitos civis e difundiram ideias liberais, constitucionalismo e cidadania.</p>", "Observe quais grupos sociais lideraram cada revolução e quais limites permaneceram."),
      criarTopico("humanas", 3, "seculo-xix-imperialismo", "Século XIX e Imperialismo", "Estude nacionalismo, unificações, independências, industrialização e colonização africana.", "Essencial", "<p>O século XIX combinou formação de Estados nacionais, expansão industrial e dominação colonial. O imperialismo dividiu a África, intensificou disputas e ampliou desigualdades globais.</p>", "Ligue economia, política e expansão territorial."),
      criarTopico("humanas", 4, "brasil-colonia", "Brasil Colônia", "Compreenda colonização, engenhos, escravidão, mineração e resistências.", "Essencial", "<p>A colonização portuguesa organizou a produção açucareira, usou trabalho escravizado indígena e africano e controlou o território por capitanias. Mineração, expansão pecuária e administração reformista alteraram a colônia.</p>", "As resistências indígenas, quilombolas e escravas também fizeram parte da história colonial."),
      criarTopico("humanas", 5, "independencia-império", "Independência e Império", "Estude 1808, 1822, Primeiro e Segundo Reinados, Regência e escravidão.", "Essencial", "<p>A vinda da família real transferiu a sede do império português para o Brasil. A independência foi conduzida por elites e preservou escravidão e concentração de terras. O Segundo Reinado trouxe centralização, café e disputas políticas.</p>", "Diferencie independência política e transformações sociais."),
      criarTopico("humanas", 6, "republica-velha", "República Velha", "Analise oligarcquias, café com leite, coronelismo, crescimento urbano e revoltas.", "Essencial", "<p>A Primeira República manteve poder nas mãos de oligarquias estaduais. A política do café com leite alternava São Paulo e Minas Gerais. Urbanização, trabalho operário e revoltas de tenentes pressionaram o sistema.</p>", "Relacione estrutura agrária e organização política."),
      criarTopico("humanas", 7, "era-vargas", "Era Vargas", "Estude o governo de 1930, Estado Novo, trabalhismo, nacionalismo e industrialização.", "Essencial", "<p>Getúlio Vargas centralizou o poder, criou leis trabalhistas e promoveu nacionalização e industrialização. O Estado Novo foi um regime autoritário, marcado por censura e repressão política.</p>", "Avalie conquistas sociais e limites democráticos ao mesmo tempo."),
      criarTopico("humanas", 8, "ditadura-redemocratizacao", "Ditadura militar e redemocratização", "Compreenda o golpe de 1964, AI-5, milagre econômico, abertura política e Constituição de 1988.", "Essencial", "<p>O regime militar suspendeu direitos, perseguiu opositores e controlou a política. A abertura política resultou em eleições diretas, partidos e Constituição Cidadã, que ampliou direitos sociais e democráticos.</p>", "Conecte economia, repressão e movimentos sociais."),
      criarTopico("humanas", 9, "cartografia-geologia", "Cartografia e geologia", "Revise escala, projeções, coordenadas, relevo e tectônica de placas.", "Essencial", "<p>Cartografia representa o espaço por meio de escalas, coordenadas, projeções e símbolos. O relevo é modelado por estruturas geológicas, agentes internos e processos externos de erosão e deposição.</p>", "Escolha a projeção certa para a finalidade do mapa."),
      criarTopico("humanas", 10, "clima-hidrografia", "Clima e hidrografia", "Analise fatores climáticos, climas brasileiros, massas de ar, rios e bacias hidrográficas.", "Essencial", "<p>Latitude, altitude, maritimidade, correntes e massas de ar definem o clima. No Brasil, chuvas e regimes fluviais influenciam agricultura, energia, abastecimento e fenômenos como secas e enchentes.</p>", "Associe clima, vegetação e atividades humanas."),
      criarTopico("humanas", 11, "populacao-urbanizacao", "População e urbanização", "Estude crescimento, migrações, metrópoles, segregação urbana e redes urbanas.", "Essencial", "<p>Dinâmica populacional depende de natalidade, mortalidade e migração. O processo de urbanização brasileiro gerou metrópoles desiguais, expansão de periferias e desafios de mobilidade, moradia e saneamento.</p>", "Observe como renda e infraestrutura moldam a ocupação urbana."),
      criarTopico("humanas", 12, "atividades-rurais-urbanas", "Atividades rurais e urbanas", "Compare agricultura, pecuária, indústria, serviços e novas tecnologias.", "Essencial", "<p>Atividades primárias exploram recursos naturais; secundárias transformam matérias-primas; terciárias prestam serviços. Modernização agrícola, agroindústria, logística e tecnologia reorganizam o espaço produtivo.</p>", "Localize os diferentes complexos produtivos no território brasileiro."),
      criarTopico("humanas", 13, "globalizacao-geopolitica", "Globalização e geopolítica", "Analise fluxos econômicos, blocos regionais, conflitos, multinacionais e soberania.", "Essencial", "<p>A globalização intensificou circulação de mercadorias, capitais, informações e pessoas. Blocos econômicos e organizações internacionais disputam influência, enquanto conflitos revelam disputas por território, recursos e poder.</p>", "Identifique quem ganha e quem perde em cada processo global."),
      criarTopico("humanas", 14, "meio-ambiente-sustentabilidade", "Meio ambiente e sustentabilidade", "Estude biomas, desmatamento, mudanças climáticas, políticas ambientais e consumo.", "Essencial", "<p>A exploração de recursos naturais gera impactos ambientais e sociais. Sustentabilidade busca equilíbrio entre meio ambiente, desenvolvimento e justiça social, envolvendo legislação, tecnologia e consumo responsável.</p>", "Diferencie preservação, conservação e desenvolvimento sustentável."),
      criarTopico("humanas", 15, "cidadania-estado-sociedade", "Cidadania, Estado e sociedade", "Compreenda direitos, participação política, movimentos sociais, identidade e desigualdade.", "Essencial", "<p>Cidadania envolve direitos civis, políticos e sociais. O Estado organiza instituições e políticas públicas, enquanto a sociedade participa por voto, movimentos, associações e controle social.</p>", "Relacione indivíduo, coletividade e instituições.")
    ]
  },

  natureza: {
    materia: "natureza",
    nome: "Ciências da Natureza e suas Tecnologias",
    icone: "🔬",
    cor: "#059669",
    descricao:
      "Química, Física e Biologia aplicadas a fenômenos naturais, tecnologia e cotidiano.",
    topicos: [
      criarTopico("natureza", 0, "metodologia-cientifica", "Metodologia científica", "Diferencie hipóteses, variáveis, controle experimental e comunicação científica.", "Essencial", "<p>A investigação científica parte de observação e problema, organiza hipóteses, testa variáveis sob controle e comunica resultados. Ciência é provisória, verificável e sujeita a revisão.</p>", "Identifique qual variável está sendo controlada ou alterada no experimento."),
      criarTopico("natureza", 1, "materia-atomos", "Matéria e átomos", "Estude propriedades, transformações físicas e químicas, modelos atômicos e partículas subatômicas.", "Essencial", "<p>A matéria tem massa e ocupa lugar no espaço. Transformações físicas não criam nova substância; químicas geram novos materiais. Átomos são formados por prótons, nêutrons e elétrons, podendo originar íons e isótopos.</p>", "Observe se houve formação de substância nova para classificar a transformação."),
      criarTopico("natureza", 2, "tabela-periodica", "Tabela periódica", "Localize famílias, períodos, número atômico e propriedades periódicas.", "Essencial", "<p>A tabela organiza os elementos por número atômico e propriedades. Famílias apresentam comportamento químico semelhante; períodos indicam camadas eletrônicas. Raio atômico, eletronegatividade e energia de ionização seguem tendências.</p>", "A distribuição eletrônica explica a posição e o comportamento do elemento."),
      criarTopico("natureza", 3, "ligacoes-quimicas", "Ligações químicas", "Compare ligações iônicas, covalentes, metálicas e intermoleculares.", "Essencial", "<p>Na ligação iônica há transferência de elétrons; na covalente, compartilhamento; na metálica, elétrons livres. Interações intermoleculares influenciam ponto de fusão, ebulição e solubilidade.</p>", "Relacione tipo de ligação às propriedades do material."),
      criarTopico("natureza", 4, "funcoes-inorganicas", "Funções inorgânicas", "Reconheça óxidos, ácidos, bases e sais por suas propriedades e nomenclatura.", "Essencial", "<p>Ácidos liberam H+ em solução aquosa; bases liberam OH-; sais resultam da neutralização; óxidos contêm oxigênio. Indicadores, corrosividade, sabor e condutividade ajudam na identificação.</p>", "Observe a fórmula e o comportamento em água."),
      criarTopico("natureza", 5, "estequiometria", "Estequiometria", "Equilibre equações, trabalhe com mol, massa molar, pureza e rendimento.", "Essencial", "<p>A estequiometria calcula quantidades de reagentes e produtos. A equação balanceada fornece proporções em mol. É preciso converter entre massa, mol e volume, além de considerar pureza e rendimento.</p>", "Comece sempre equilibrando a equação química."),
      criarTopico("natureza", 6, "solucoes", "Soluções", "Estude concentração, diluição, misturas, solubilidade e condutividade.", "Essencial", "<p>Soluções são misturas homogêneas de soluto e solvente. Concentração pode ser expressa em g/L, mol/L e percentual. Diluição reduz concentração adicionando solvente; solubilidade depende de temperatura e substâncias.</p>", "Em diluição, a quantidade de soluto permanece constante."),
      criarTopico("natureza", 7, "termoquimica", "Termoquímica", "Analise processos endotérmicos, exotérmicos, entalpia, lei de Hess e combustíveis.", "Essencial", "<p>Reações exotérmicas liberam energia; endotérmicas absorvem. A variação de entalpia indica o balanço energético. A lei de Hess permite calcular energia em etapas. Combustíveis são avaliados por poder calorífico e impactos ambientais.</p>", "Observe o sinal da variação de entalpia e o estado das substâncias."),
      criarTopico("natureza", 8, "cinetica-equilibrio", "Cinética e equilíbrio químico", "Compreenda velocidade de reação, energia de ativação, reversibilidade e constante de equilíbrio.", "Essencial", "<p>Temperatura, concentração, superfície de contato e catalisadores alteram a velocidade. No equilíbrio, reações direta e inversa ocorrem simultaneamente. O princípio de Le Chatelier prevê deslocamentos por concentração, pressão e temperatura.</p>", "Catalisador acelera, mas não desloca o equilíbrio."),
      criarTopico("natureza", 9, "eletroquimica", "Eletroquímica", "Estude oxirredução, pilhas, eletrólise e potenciais padrão.", "Essencial", "<p>Nas reações de oxirredução ocorrem perda e ganho de elétrons. Pilhas convertem energia química em elétrica; eletrólise usa energia elétrica para promover reação não espontânea. O potencial padrão indica a tendência de redução.</p>", "Identifique o ânodo, o cátodo e o sentido dos elétrons."),
      criarTopico("natureza", 10, "cinematica", "Cinemática", "Estude MRU, MRUV, gráficos, lançamentos e movimentos relativos.", "Essencial", "<p>A cinemática descreve movimentos sem analisar suas causas. No MRU a velocidade é constante; no MRUV há aceleração constante. Gráficos de posição, velocidade e aceleração são muito cobrados.</p>", "A área sob o gráfico velocidade-tempo corresponde ao deslocamento."),
      criarTopico("natureza", 11, "dinamica", "Dinâmica", "Aplique as leis de Newton, forças, peso, atrito e ações em corpos.", "Essencial", "<p>A dinâmica relaciona força, massa e aceleração. A primeira lei trata da inércia; a segunda relaciona F = m·a; a terceira trata de ação e reação. Peso, normal, tração e atrito aparecem em situações cotidianas.</p>", "Faça o diagrama de corpo livre antes de montar as equações."),
      criarTopico("natureza", 12, "trabalho-energia-momento", "Trabalho, energia e momento", "Analise energia cinética, potencial, conservação, potência, impulso e colisões.", "Essencial", "<p>Trabalho transfere energia por meio de uma força. Energia mecânica pode se conservar na ausência de forças dissipativas. Impulso altera o momento linear e é fundamental para estudar colisões.</p>", "Diferencie energia conservada e energia dissipada."),
      criarTopico("natureza", 13, "termologia", "Termologia", "Estude temperatura, calor, expansão, calorimetria, mudanças de estado e gases.", "Essencial", "<p>Temperatura mede o grau de agitação das partículas; calor é energia em trânsito. Calor sensível altera temperatura; calor latente muda estado. Gases ideais obedecem a relações entre pressão, volume e temperatura.</p>", "Verifique se a substância está mudando de estado ou apenas de temperatura."),
      criarTopico("natureza", 14, "ondulatoria", "Ondulatória", "Compreenda propagação, reflexão, refração, difração, interferência, som e efeito Doppler.", "Essencial", "<p>Ondas transportam energia sem transporte líquido de matéria. Características como frequência, comprimento de onda, amplitude e velocidade descrevem o fenômeno. O som precisa de meio material; luz pode propagar-se no vácuo.</p>", "Relacione frequência, comprimento de onda e velocidade de propagação."),
      criarTopico("natureza", 15, "optica", "Óptica", "Estude reflexão, refração, espelhos, lentes, visão humana e instrumentos ópticos.", "Essencial", "<p>A reflexão ocorre quando a luz retorna ao mesmo meio; a refração ocorre ao mudar de meio e velocidade. Espelhos e lentes formam imagens reais ou virtuais, ampliadas ou reduzidas, conforme posição e curvatura.</p>", "Use os raios notáveis para construir a imagem."),
      criarTopico("natureza", 16, "eletricidade", "Eletricidade", "Aplique corrente, tensão, resistência, potência, circuitos e associações.", "Essencial", "<p>A corrente elétrica é o movimento ordenado de cargas. A lei de Ohm relaciona tensão, resistência e corrente. Em circuitos, é essencial reconhecer associações em série e paralelo e calcular potência consumida.</p>", "No paralelo, todos os componentes ficam sob a mesma tensão."),
      criarTopico("natureza", 17, "citologia", "Citologia", "Estude membrana, organelas, núcleo, divisão celular e diferenças entre células.", "Essencial", "<p>A célula é a unidade estrutural e funcional dos seres vivos. Membrana controla trocas; mitocôndrias produzem ATP; ribossomos sintetizam proteínas; núcleo armazena informação genética. Mitose gera células semelhantes; meiose produz células com metade dos cromossomos.</p>", "Associe cada organela à sua função principal."),
      criarTopico("natureza", 18, "bioquimica-metabolismo", "Bioquímica e metabolismo celular", "Analise biomoléculas, enzimas, respiração celular e fotossíntese.", "Essencial", "<p>Carboidratos, proteínas, lipídios e ácidos nucleicos desempenham funções estruturais e energéticas. Enzimas aceleram reações. Respiração celular libera energia; fotossíntese armazena energia solar em moléculas orgânicas.</p>", "Compare local, reagentes e produtos da fotossíntese e da respiração."),
      criarTopico("natureza", 19, "genetica", "Genética", "Estude DNA, RNA, genes, leis de Mendel, herança, mutações e biotecnologia.", "Essencial", "<p>Genes são sequências de DNA que codificam características. Meiose e fecundação explicam a variabilidade. As leis de Mendel descrevem segregação e distribuição independente de alelos. Mutações e tecnologias genéticas ampliam as possibilidades de estudo.</p>", "Use quadros de cruzamento e probabilidade."),
      criarTopico("natureza", 20, "evolucao", "Evolução", "Compreenda seleção natural, adaptação, especiação, evidências e extinções.", "Essencial", "<p>A evolução é a mudança de características hereditárias ao longo das gerações. Seleção natural favorece indivíduos mais adaptados ao ambiente. Fósseis, anatomia comparada e moléculas são evidências do parentesco evolutivo.</p>", "Adaptação não é escolha consciente do organismo."),
      criarTopico("natureza", 21, "ecologia", "Ecologia", "Analise níveis ecológicos, cadeias, teias, ciclos, sucessão e impactos ambientais.", "Essencial", "<p>Ecologia estuda relações entre organismos e ambiente. Cadeias e teias alimentares transferem matéria e energia. Ciclos biogeoquímicos movem nutrientes, enquanto poluição, introdução de espécies e perda de habitat alteram ecossistemas.</p>", "Energia diminui ao longo dos níveis tróficos; matéria é reciclada."),
      criarTopico("natureza", 22, "fisiologia-humana", "Fisiologia humana", "Estude sistemas do corpo, digestão, circulação, respiração, excreção e regulação hormonal.", "Essencial", "<p>Os sistemas trabalham de forma integrada para manter a homeostase. Nutrientes são digeridos, transportados pelo sangue, utilizados pelas células e resíduos são eliminados. Hormônios regulam funções por retroalimentação.</p>", "Siga o percurso da matéria e do oxigênio pelo organismo."),
      criarTopico("natureza", 23, "imunologia-biotecnologia", "Imunologia e biotecnologia", "Compreenda imunidade, vacinas, anticorpos, transgênicos e questões éticas.", "Essencial", "<p>A imunidade inata atua rapidamente; a adaptativa produz resposta específica e memória. Vacinas estimulam defesa sem causar a doença. Biotecnologia utiliza organismos e processos biológicos em medicina, agricultura e indústria.</p>", "Relacione benefícios, riscos e impactos sociais das tecnologias.")
    ]
  },

  matematica: {
    materia: "matematica",
    nome: "Matemática e suas Tecnologias",
    icone: "📐",
    cor: "#f97316",
    descricao:
      "Raciocínio lógico, álgebra, geometria, análise de dados e aplicações matemáticas.",
    topicos: [
      criarTopico("matematica", 0, "conjuntos-numeros", "Conjuntos e números", "Trabalhe com conjuntos, intervalos, conjuntos numéricos e operações.", "Essencial", "<p>Conjuntos podem ser representados por listagem, diagrama ou propriedade. União reúne elementos; interseção representa elementos comuns; diferença retira elementos. Conjuntos numéricos incluem naturais, inteiros, racionais, irracionais e reais.</p>", "Desenhe diagramas de Venn para visualizar relações."),
      criarTopico("matematica", 1, "funcoes", "Funções", "Compreenda domínio, imagem, crescimento, composição e função inversa.", "Essencial", "<p>Função associa cada elemento do domínio a um único elemento no contradomínio. Gráficos e tabelas mostram crescimento, decrescimento, zeros e valores máximos ou mínimos. Composição e inversa são operações fundamentais.</p>", "Leia o gráfico antes de procurar fórmulas."),
      criarTopico("matematica", 2, "funcao-afim", "Função afim", "Estude f(x) = ax + b, taxa de variação, gráficos e situações proporcionais.", "Essencial", "<p>A função afim tem taxa de variação constante. O coeficiente a indica crescimento ou decrescimento; b indica o ponto onde a reta corta o eixo y. É comum em custos, salários, consumo e movimento uniforme.</p>", "Use dois pontos para encontrar a lei da função."),
      criarTopico("matematica", 3, "funcao-quadratica", "Função quadrática", "Analise parábola, raízes, vértice, máximo, mínimo e aplicações.", "Essencial", "<p>A função quadrática tem forma f(x) = ax² + bx + c. O sinal de a define a concavidade. As raízes dependem do discriminante; o vértice fornece x = -b/2a e valor máximo ou mínimo. Aparece em trajetórias, áreas e lucros.</p>", "O vértice é o ponto principal em problemas de máximo ou mínimo."),
      criarTopico("matematica", 4, "funcao-exponencial", "Função exponencial", "Estude crescimento, decaimento, juros e equações exponenciais.", "Essencial", "<p>A função exponencial tem forma f(x) = a·b^x, com b positivo e diferente de 1. Quando b é maior que 1, há crescimento; quando está entre 0 e 1, há decaimento. É usada em juros, populações e meia-vida.</p>", "Identifique a taxa percentual e o fator multiplicativo."),
      criarTopico("matematica", 5, "logaritmos", "Logaritmos", "Aplique definição, propriedades, escala logarítmica e equações logarítmicas.", "Essencial", "<p>Logaritmo responde à questão: a que expoente devemos elevar a base para obter um número? As propriedades operatórias simplificam produtos, quocientes e potências. Escalas logarítmicas aparecem em Richter, pH e decibéis.</p>", "Transforme logaritmo em potência sempre que possível."),
      criarTopico("matematica", 6, "pa-pg", "PA e PG", "Trabalhe com termos, soma, crescimento e aplicações de progressões.", "Essencial", "<p>Na PA a diferença entre termos consecutivos é constante; na PG a razão multiplica os termos. Fórmulas do termo geral e da soma permitem resolver situações de acúmulo, crescimento e pagamentos.</p>", "Escreva os primeiros termos para reconhecer o padrão."),
      criarTopico("matematica", 7, "matrizes-sistemas", "Matrizes, determinantes e sistemas", "Resolva sistemas lineares e interprete matrizes em tabelas e transformações.", "Essencial", "<p>Matrizes organizam dados em linhas e colunas; determinantes estão associados a sistemas e áreas. Sistemas lineares podem ter solução única, infinitas soluções ou nenhuma solução, conforme a relação entre equações.</p>", "Escalonamento facilita encontrar as incógnitas."),
      criarTopico("matematica", 8, "polinomios", "Polinômios", "Estude raízes, divisão, teorema do resto e dispositivo de Briot-Ruffini.", "Essencial", "<p>Polinômios são expressões algébricas com potências da variável. Valor numérico, raízes e divisão aparecem com frequência. Briot-Ruffini simplifica a divisão por binômios da forma x - a.</p>", "Teste raízes prováveis para decompor o polinômio."),
      criarTopico("matematica", 9, "analise-combinatoria", "Análise combinatória", "Aplique princípio multiplicativo, fatorial, arranjos e combinações.", "Essencial", "<p>A contagem organiza possibilidades. O princípio multiplicativo multiplica escolhas sucessivas. Permutações rearranjam elementos; arranjos consideram ordem; combinações não consideram. Identificar se a ordem importa é o ponto central.</p>", "Pergunte se trocar a ordem gera uma possibilidade diferente."),
      criarTopico("matematica", 10, "probabilidade", "Probabilidade", "Calcule eventos, união, interseção, complementar e probabilidade condicional.", "Essencial", "<p>A probabilidade é a razão entre casos favoráveis e possíveis, quando todos são igualmente prováveis. Eventos independentes multiplicam probabilidades; eventos mutuamente excludentes somam. Probabilidade condicional restringe o espaço amostral.</p>", "Leia se o experimento é com ou sem reposição."),
      criarTopico("matematica", 11, "geometria-plana", "Geometria plana", "Revise triângulos, quadriláteros, circunferência, áreas e semelhança.", "Essencial", "<p>Geometria plana estuda figuras em duas dimensões. Ângulos, lados, congruência e semelhança aparecem em demonstrações e cálculos. Áreas de triângulos, quadriláteros e círculos são muito cobradas.</p>", "Identifique relações de proporcionalidade antes de aplicar fórmulas."),
      criarTopico("matematica", 12, "geometria-espacial", "Geometria espacial", "Calcule volumes e áreas de prismas, cilindros, cones, pirâmides e esferas.", "Essencial", "<p>Geometria espacial estuda sólidos. Prismas e cilindros têm volume igual à área da base vezes altura. Cones e pirâmides levam em conta um terço dessa relação; a esfera possui fórmulas próprias.</p>", "Separe cálculo de área superficial e volume."),
      criarTopico("matematica", 13, "geometria-analitica", "Geometria analítica", "Trabalhe com distância, ponto médio, retas, circunferência e posições relativas.", "Essencial", "<p>A geometria analítica relaciona álgebra e geometria por meio de coordenadas. Distância, ponto médio, coeficiente angular e equações de reta permitem resolver problemas de posição e interseção.</p>", "Desenhe o plano cartesiano para interpretar os sinais."),
      criarTopico("matematica", 14, "trigonometria", "Trigonometria", "Estude razões no triângulo, lei dos senos, lei dos cossenos e ciclo trigonométrico.", "Essencial", "<p>Seno, cosseno e tangente relacionam lados e ângulos. A lei dos senos e a lei dos cossenos generalizam o estudo para triângulos não retângulos. No ciclo, os sinais variam conforme o quadrante.</p>", "Verifique se o triângulo é retângulo antes de escolher a ferramenta."),
      criarTopico("matematica", 15, "estatistica", "Estatística", "Analise médias, medianas, moda, gráficos, dispersão e interpretação de dados.", "Essencial", "<p>Estatística organiza, resume e interpreta dados. Média, mediana e moda medem tendência central; amplitude e desvio indicam dispersão. Gráficos devem ser lidos com atenção à escala, amostra e representatividade.</p>", "Sempre observe se os dados são brutos, agrupados ou ponderados.")
    ]
  },

  redacao: {
    materia: "redacao",
    nome: "Redação",
    icone: "✍️",
    cor: "#dc2626",
    descricao:
      "Estrutura dissertativo-argumentativa, competências, argumentação, coesão e proposta de intervenção.",
    topicos: [
      criarTopico("redacao", 0, "dissertacao-argumentativa", "Dissertação argumentativa", "Organize introdução, dois desenvolvimentos e conclusão com posição clara.", "Essencial", "<p>A redação do ENEM defende um ponto de vista sobre o tema. A introdução apresenta contexto, tese e, quando adequado, visão geral. Os parágrafos de desenvolvimento trazem argumentos e repertórios; a conclusão retoma a tese e propõe intervenção.</p>", "Escreva parágrafos completos, sem texto em tópicos."),
      criarTopico("redacao", 1, "competencia-1", "Competência 1 — Norma culta", "Domine acentuação, ortografia, morfologia, sintaxe e pontuação formal.", "Essencial", "<p>A competência 1 avalia o domínio da modalidade escrita formal. Desvios graves de grafia, acentuação, concordância, regência e pontuação reduzem a nota. Escreva com frases claras e revise o texto ao final.</p>", "Deixe alguns minutos exclusivamente para revisão."),
      criarTopico("redacao", 2, "competencia-2", "Competência 2 — Tema e estrutura", "Compreenda o tema, selecione argumentos e organize a estrutura dissertativa.", "Essencial", "<p>A competência 2 verifica compreensão do tema, seleção de argumentos e organização do texto. Fuja do lugar comum, mantenha foco no problema e estruture ideias de modo lógico e progressivo.</p>", "Use somente argumentos relacionados diretamente ao tema."),
      criarTopico("redacao", 3, "competencia-3", "Competência 3 — Argumentação", "Defenda seu ponto de vista com argumentos consistentes e repertórios válidos.", "Essencial", "<p>A competência 3 exige posicionamento claro e desenvolvimento convincente. Argumentos podem vir de dados, fatos históricos, leis, teorias, referências artísticas e experiências sociais. O repertório precisa estar integrado à defesa.</p>", "Explique como o repertório sustenta o argumento."),
      criarTopico("redacao", 4, "competencia-4", "Competência 4 — Coesão e coerência", "Use conectivos, retomadas e progressão textual para unir as ideias.", "Essencial", "<p>Coesão conecta palavras, frases e parágrafos; coerência garante sentido lógico. Conectivos adequados e retomadas por sinônimos ou expressões evitam repetições e tornam o texto fluido.</p>", "Não use conectivos sem relação lógica real."),
      criarTopico("redacao", 5, "competencia-5", "Competência 5 — Proposta de intervenção", "Elabore proposta completa com agente, ação, meio, finalidade e detalhamento.", "Essencial", "<p>A conclusão do ENEM precisa apresentar proposta de intervenção relacionada ao tema. Uma boa proposta indica quem deve agir, o que fazer, como fazer, com qual objetivo e, idealmente, de que forma será executada.</p>", "Evite propostas genéricas como conscientizar, fiscalizar ou melhorar."),
      criarTopico("redacao", 6, "introducao-desenvolvimento-conclusao", "Introdução, desenvolvimento e conclusão", "Construa cada parte da redação com funções bem definidas.", "Essencial", "<p>A introdução contextualiza o tema e apresenta a tese. O desenvolvimento expõe argumentos com repertórios. A conclusão retoma a importância do problema e apresenta solução viável, sem repetir mecanicamente o que já foi dito.</p>", "Cada parágrafo deve cumprir uma função clara."),
      criarTopico("redacao", 7, "repertorios", "Repertórios produtivos", "Use dados, leis, filosofia, história, literatura, sociologia e atualidades.", "Essencial", "<p>Repertórios ampliam a argumentação quando bem relacionados ao tema. Constituição, ONU, filósofos, movimentos sociais, dados estatísticos e obras artísticas podem enriquecer a redação, desde que sejam explicados.</p>", "Repertório citado sem relação com o argumento quase não soma pontos."),
      criarTopico("redacao", 8, "conectivos", "Conectivos e articulação", "Selecione conectivos de causa, consequência, oposição, adição e finalidade.", "Essencial", "<p>Conectivos orientam a leitura e mostram relações entre ideias. Além de expressões prontas, é possível articular por meio de retomadas, sinônimos, pronomes e repetição controlada de termos-chave.</p>", "Varie as articulações para evitar texto robótico."),
      criarTopico("redacao", 9, "erros-comuns-treino", "Erros graves e estratégia de treino", "Evite trechos prontos, texto desconexo, proposta vazia e falta de revisão.", "Essencial", "<p>Entre os principais riscos estão fuga ao tema, estrutura inadequada, argumentos frágeis, proposta ausente e linguagem informal. Treine com temas variados, cronometre a escrita, revise e compare com boas redações.</p>", "Escreva pelo menos uma redação completa por semana e corrija em etapas.")
    ]
  }
};